version: '3'

services:
  redis1:
    image: redis:6.0
    volumes:
      - /home/monitoramento/redis/data1:/data
    container_name: redis1
    ports:
      - "6379:6379"

  redis2:
    image: redis:6.0
    volumes:
      - /home/monitoramento/redis/data2:/data
    container_name: redis2
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis1 6379
    depends_on:
      - redis1